version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .\www\:/var/www/html/:rw
      - .\conf\nginx\conf.d\:/etc/nginx/conf.d/:ro
      - .\conf\nginx\nginx.conf:/etc/nginx/nginx.conf:ro
      - .\log\nginx\:/var/log/nginx/:rw
    networks:
      - net-php56
      - net-php72

  php72:
    image: php:7.2-fpm
    expose:
      - "9000"
    volumes:
      - .\www\:/var/www/html/:rw
      - .\conf\php72\php.ini:/usr/local/etc/php/php.ini:ro
      - .\conf\php72\php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - .\log\php72\:/var/log/php-fpm/:rw
    networks:
      - net-php72
      - net-mysql
      - net-mongo
      - net-redis

  php56:
    image: php:5.6-fpm
    expose:
      - "9000"
    volumes:
      - .\www\:/var/www/html/:rw
      - .\conf\php56\php.ini:/usr/local/etc/php/php.ini:ro
      - .\conf\php56\php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - .\log\php56\:/var/log/php-fpm/:rw
    networks:
      - net-php56
      - net-mysql
      - net-mongo
      - net-redis

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - .\conf\mysql\mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - .\mysql\:/var/lib/mysql/:rw
      - .\log\mysql\:/var/log/mysql/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - net-mongo

  redis:
    image: redis:latest
    networks:
      - net-redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - net-mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8081:80"
    networks:
      - net-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  net-php56:
  net-php72:
  net-mysql:
  net-mongo:
  net-redis: